#!/bin/bash

#Disable the touchpad from waking up the system from sleep
TPAD=`cat /proc/acpi/wakeup | grep TPAD | grep enabled | tr -d '\n'`
if [ -n "$TPAD" ]
then
   echo "TPAD" > /proc/acpi/wakeup
fi

ETPA=`cat /proc/acpi/wakeup | grep ETPA | grep enabled | tr -d '\n'`
if [ -n "$ETPA" ]
then
   echo "ETPA" > /proc/acpi/wakeup
fi

#Change permissions on backlight controls
chgrp plugdev /sys/class/backlight/intel_backlight/brightness
chmod 664 /sys/class/backlight/intel_backlight/brightness

#Calibrate the touchpad
CALIBRATE=`find /sys/devices/* -name 'calibrate' | head -1`
if [ -n "$CALIBRATE" ]
then
    echo 1 > "$CALIBRATE"
fi

